### PR TITLE
Add support for ripping to SD2SP2 adapter

### PR DESCRIPTION
**Pull request by ThadHouse**
Added as a 3rd button to select.

Sorry about the whitespace changes, my editor is set to automatically trim trailing whitespace. I can remove it if needed.

### CODE REVIEW

**Comment by ThadHouse** [comment]
I still need to test this, which I will do tonight.

**Comment by emukidid** [comment]
Resolve conflicts and I'll try it out too :)

**Comment by ThadHouse** [comment]
Ok. Fixed the conflicts.

**Comment by emukidid** [comment]
Minor conflict crept in after I merged in the other more thoroughly tested change req, can you update yours and I'll hit merge on it as well. Thanks!

**Comment by ThadHouse** [comment]
Updated. We're you able to test it? My adapter didn't work, getting a new one shipped, but wasn't able to test it.

**Comment by emukidid** [comment]
Yep, I've tested it and it works just fine.

**Pull request merged**
